### ISSUE TITLE
Panel crashes when no plugins are active

### ISSUE THREAD

**Issue by tom2901** [jetspace/desktop#124]
If you deactivate **all** plugins the panel crashes.

**Comment by mame98** [comment]
Confirmed, but the problem is *NOT* that you have no plugins, there is a problem when there are no plugins which populate the right side...

Investigation running ;)

**Comment by mame98** [comment]
Currently considering rewriting plugin support, because there are a lot of minor issues...

**Comment by mame98** [comment]
There were just a stupid issue, fixed!

BTW: Still planning to rewrite parts of the plugin system to make it somehow similar to the settings plugins...
